environment:
    nodejs_version: ''
    auth_token: yOP1Q87yi+ABH6qSrkuEg5f2GPMrF2yNaQDPOnUIBspKd7LliF1QZvzhV8QIc+mZ

platform:
 - x64

cache:
 - node_modules
 - '%APPDATA%\npm-cache'
 - '%USERPROFILE%\.electron'

init:
 - git config --global core.autocrlt input
 - set

install:
 - ps: Install-Product node $env:nodejs_version

test_script:
  - node --version
  - npm --version

before_build:
  - cd ./cs-front-end
  - npm install

build_script:
 - npm run dist

test: off

deploy:
    release: myproduct-v$(APPVEYOR_BUILD_VERSION)
    description: 'Release description'
    provider: GitHub
    auth_token:
      secure: $env:auth_token
    draft: false
    prerelease: false
    on:
      branch: master 
      APPVEYOR_REPO_TAG: true  